- name: Run app.py on Azure VM
  hosts: azure_vm
  become: yes  # Run as sudo
  tasks:

    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    - name: Create a virtual environment
      command: python3 -m venv /home/hemanthvm2/netbott/venv

    - name: Install required Python libraries inside the virtual environment
      command: /home/hemanthvm2/netbott/venv/bin/pip install flask openai requests certifi urllib3

    - name: Run app.py in the background using the virtual environment
      command: nohup /home/hemanthvm2/netbott/venv/bin/python /home/hemanthvm2/netbott/app.py > /home/hemanthvm2/netbott/app.log 2>&1 &
      args:
        chdir: /home/hemanthvm2/netbott  # Change to the directory where app.py is located
      async: 1000
      poll: 0
